package applier

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/sylphy/git-switch/core/config"
)

type SSHApplier struct {
	sshDir string
}

func NewSSHApplier(sshDir string) SSHApplier {
	return SSHApplier{sshDir: sshDir}
}

func (a SSHApplier) ApplySSHConfig(ctx context.Context, profile config.Profile) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	if profile.SSH == nil {
		return errors.New("profile has no ssh configuration")
	}
	if len(profile.SSH.Hosts) == 0 {
		return errors.New("ssh hosts must not be empty")
	}

	sshDir, err := config.ExpandHome(a.sshDir)
	if err != nil {
		return err
	}
	configDir := filepath.Join(sshDir, "config.d")
	if err := os.MkdirAll(configDir, 0o700); err != nil {
		return fmt.Errorf("create ssh config.d: %w", err)
	}

	generated := generateSSHConfig(profile)
	if err := os.WriteFile(filepath.Join(configDir, "git-switch"), []byte(generated), 0o600); err != nil {
		return fmt.Errorf("write generated ssh config: %w", err)
	}
	return ensureInclude(filepath.Join(sshDir, "config"))
}

func generateSSHConfig(profile config.Profile) string {
	ssh := profile.SSH
	alias := ssh.HostAlias
	if alias == "" {
		alias = ssh.Hosts[0]
	}
	return fmt.Sprintf(
		"# Generated by git-switch. Do not edit manually.\n# Profile: %s\n\nHost %s\n    HostName %s\n    User git\n    IdentityFile %s\n    IdentitiesOnly yes\n",
		profile.Profile.Name, alias, ssh.Hosts[0], ssh.KeyFile,
	)
}

func ensureInclude(path string) error {
	const includeLine = "Include config.d/*"
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return os.WriteFile(path, []byte(includeLine+"\n"), 0o600)
	}
	if err != nil {
		return fmt.Errorf("read ssh config: %w", err)
	}
	content := string(data)
	if hasUncommentedLine(content, includeLine) {
		return nil
	}
	return os.WriteFile(path, []byte(includeLine+"\n"+content), 0o600)
}

func hasUncommentedLine(content, target string) bool {
	for _, line := range strings.Split(content, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == target {
			return true
		}
	}
	return false
}
