package applier

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode"

	"github.com/sylphy/git-switch/core/config"
)

type SSHApplier struct {
	sshDir        string
	generatedPath string
}

func NewSSHApplier(sshDir string) SSHApplier {
	return SSHApplier{sshDir: sshDir}
}

func (a *SSHApplier) ApplySSHConfig(ctx context.Context, profile config.Profile) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	if profile.SSH == nil {
		return errors.New("profile has no ssh configuration")
	}
	keyFile, err := resolveSSHKeyFile(profile.SSH.KeyFile)
	if err != nil {
		return err
	}
	if err := validateSSHConfig(profile.SSH); err != nil {
		return err
	}

	sshDir, err := config.ExpandHome(a.sshDir)
	if err != nil {
		return err
	}
	configDir := filepath.Join(sshDir, "config.d")
	if err := os.MkdirAll(configDir, 0o700); err != nil {
		return fmt.Errorf("create ssh config.d: %w", err)
	}

	a.generatedPath = filepath.Join(configDir, "git-switch")
	generated := generateSSHConfig(profile, keyFile)
	if err := os.WriteFile(a.generatedPath, []byte(generated), 0o600); err != nil {
		return fmt.Errorf("write generated ssh config: %w", err)
	}
	return ensureInclude(filepath.Join(sshDir, "config"))
}

func (a *SSHApplier) Revert() error {
	if a.generatedPath != "" {
		if err := os.Remove(a.generatedPath); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("remove generated ssh config: %w", err)
		}
		a.generatedPath = ""
	}
	return nil
}

func validateSSHConfig(ssh *config.SSHConfig) error {
	if len(ssh.Hosts) == 0 {
		return errors.New("ssh hosts must not be empty")
	}
	if !validSSHPattern(ssh.KeyFile) {
		return fmt.Errorf("invalid ssh key file %q", ssh.KeyFile)
	}
	if ssh.HostAlias != "" && !validSSHPattern(ssh.HostAlias) {
		return fmt.Errorf("invalid ssh host alias %q", ssh.HostAlias)
	}
	for _, host := range ssh.Hosts {
		if !validSSHPattern(host) {
			return fmt.Errorf("invalid ssh host %q", host)
		}
	}
	return nil
}

func validSSHPattern(value string) bool {
	if value == "" {
		return false
	}
	for _, r := range value {
		if unicode.IsSpace(r) || r == '#' {
			return false
		}
	}
	return true
}

func resolveSSHKeyFile(path string) (string, error) {
	keyFile, err := config.ExpandHome(path)
	if err != nil {
		return "", fmt.Errorf("expand ssh key file %q: %w", path, err)
	}
	return keyFile, nil
}

func generateSSHConfig(profile config.Profile, keyFile string) string {
	ssh := profile.SSH
	var sb strings.Builder
	sb.WriteString("# Generated by git-switch. Do not edit manually.\n")
	sb.WriteString(fmt.Sprintf("# Profile: %s\n", profile.Profile.Name))

	for _, host := range ssh.Hosts {
		alias := ssh.HostAlias
		if alias == "" {
			alias = host
		}
		sb.WriteString(fmt.Sprintf(
			"\nHost %s\n    HostName %s\n    User git\n    IdentityFile %s\n    IdentitiesOnly yes\n",
			alias, host, keyFile,
		))
	}
	return sb.String()
}

func ensureInclude(path string) error {
	const includeLine = "Include config.d/*"
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return os.WriteFile(path, []byte(includeLine+"\n"), 0o600)
	}
	if err != nil {
		return fmt.Errorf("read ssh config: %w", err)
	}
	content := string(data)
	if hasUncommentedLine(content, includeLine) {
		return nil
	}
	mode := os.FileMode(0o600)
	if info, err := os.Stat(path); err == nil {
		mode = info.Mode().Perm()
	}
	return os.WriteFile(path, []byte(includeLine+"\n"+content), mode)
}

func hasUncommentedLine(content, target string) bool {
	for _, line := range strings.Split(content, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == target {
			return true
		}
	}
	return false
}
